### ISSUE TITLE
bootstrap

### ISSUE THREAD

**Issue by BelphegorPrime** [jorge07/symfony3-docker-starter#2]
hi,

after docker compose as you describe, comes on the server address to an bootstrap.php.cache error

( ! ) Fatal error: Uncaught RuntimeException: Unable to create the cache directory (/app/var/cache/prod) in /app/var/bootstrap.php.cache on line 2517
( ! ) RuntimeException: Unable to create the cache directory (/app/var/cache/prod) in /app/var/bootstrap.php.cache on line 2517
Call Stack
# Time    Memory  Function    Location

1   0.0002  357496  {main}( )   .../app.php:0
2   0.0187  652344  Symfony\Component\HttpKernel\Kernel->handle( )  .../app.php:28
3   0.0187  652344  Symfony\Component\HttpKernel\Kernel->boot( )    .../bootstrap.php.cache:2298
4   0.0205  666464  Symfony\Component\HttpKernel\Kernel->initializeContainer( ) .../bootstrap.php.cache:2267
5   0.0208  667992  Symfony\Component\HttpKernel\Kernel->buildContainer( )  .../bootstrap.php.cache:2478

Do you have any solution? ;)

**Comment by jorge07** [comment]
Hi @BelphegorPrime,
thanks a lot for the report, I fix it on commit f0b4b7371f54778cba8d67cc981dd15e5de45f65

**Comment by jorge07** [comment]
I'll close the issue feel free to reopen if need it

**Comment by BelphegorPrime** [comment]
( ! ) Fatal error: Cannot declare interface Symfony\Component\DependencyInjection\ContainerAwareInterface, because the name is already in use in /app/var/cache/prod/classes.php on line 6801
Call Stack

# Time    Memory  Function    Location

1   0.0000  356976  {main}( )   .../app.php:0
2   0.0170  651480  Symfony\Component\HttpKernel\Kernel->handle( )  .../app.php:28
3   0.0170  651480  Symfony\Component\HttpKernel\Kernel->boot( )    .../bootstrap.php.cache:2298
4   0.0170  651480  Symfony\Component\HttpKernel\Kernel->doLoadClassCache( )    .../bootstrap.php.cache:2264
5   0.0171  652568  Symfony\Component\ClassLoader\ClassCollectionLoader::load( )    .../bootstrap.php.cache:2419

**Comment by BelphegorPrime** [comment]
Hi @jorge07 only you can reopen the issue.

**Comment by jorge07** [comment]
Did you run: `docker exec - it symfony_php bin/console c:c - - env=prod`?

**Comment by BelphegorPrime** [comment]
no but after execution 

( ! ) Fatal error: Uncaught InvalidArgumentException: The directory "/app/var/cache/prod/annotations" is not writable. in /app/vendor/doctrine/cache/lib/Doctrine/Common/Cache/FileCache.php on line 92
( ! ) InvalidArgumentException: The directory "/app/var/cache/prod/annotations" is not writable. in /app/vendor/doctrine/cache/lib/Doctrine/Common/Cache/FileCache.php on line 92
Call Stack

# Time    Memory  Function    Location

1   0.0092  1527152 Symfony\Component\Debug\ErrorHandler->handleException( )    .../ErrorHandler.php:0
2   0.0109  1607376 Symfony\Component\Debug\ErrorHandler->handleException( )    .../ErrorHandler.php:546

**Comment by BelphegorPrime** [comment]
thanks for your fast help ;)

**Comment by jorge07** [comment]
Oks try with warm command `docker exec - it symfony_php bin/console c:w - - env=prod`

I think it could be an issue because you are using a Linux distribution right, I never test it on that. But I'll this week and add a Travis scenario. 

Thanks to you for the feedback

**Comment by BelphegorPrime** [comment]
yeah i use a linux ^^

but the warm command changed nothing. Same error.

**Comment by jorge07** [comment]
Jumm, I'm in the mountain, this night I'll try on my pc. Sorry. It's a permissions issue.

**Comment by BelphegorPrime** [comment]
No Problem. 
That's just what I was thinking. Unfortunately I have no overview of your code.

**Comment by jorge07** [comment]
It's tested on Linux and I update the documentation. It's supposed to be working now, thanks to https://github.com/jorge07/symfony3-docker-starter/pull/5
